### ISSUE TITLE
我很喜欢这个主题，但是感觉宽度有点小，这个怎么调整呢

### ISSUE THREAD

**Issue by wsy1033** [gilbertohasnofb/typora-panda-theme#1]
我很喜欢这个主题，但是感觉宽度有点小，这个怎么调整呢

Google Translate: I like this theme very much, but the width is a bit small, how to adjust this

**Comment by gilbertohasnofb** [comment]
Hello, thanks for your message. Unfortunately I do not speak Chinese, but I understand your question through Google Translate. To change the width, open the file `panda.css `, and edit lines 1303 and 1313: `max-width: 800px;`

Change `800px` to a higher value such as `1000px` or `1200px`, for instance. This will change the width of the theme.

Let me know if this works.

---- 

您好，谢谢您的留言。 不幸的是我不会说中文，但我正在使用Google翻译。 要更改宽度，请打开文件panda.css，然后编辑第1303和1313行: `max-width: 800px;`

例如，将“ 800px”更改为更高的值，例如“ 1000px”或“ 1200px”。 这将改变主题的宽度。

让我知道这个是否奏效。

**Comment by aoozoo** [comment]
我也非常喜欢这个主题，我想要图片的宽度自适应宽度，请问怎么修改？

I also like this theme very much. I want the width of the image to adapt to the width. How can I modify it?

**Comment by gilbertohasnofb** [comment]
@aoozoo Have you tried the solution above? You can set `max-width` to any number of pixels.

您是否尝试过上述解决方案? 您可以将变量`max-width`设置为任意数量的像素。

**Comment by aoozoo** [comment]
我想要的是图片自动拉伸宽度，适配主题的宽度，如果图片太小

**Comment by aoozoo** [comment]
我想要的是图片自动拉伸宽度，适配主题的宽度，如果图片太小

**Comment by gilbertohasnofb** [comment]
我不知道如何自动执行此操作，我只对 `max-width` 使用固定值
