### ISSUE TITLE
inline codeblock

### ISSUE THREAD

**Issue by uninstallHahaha** [gilbertohasnofb/typora-panda-theme#2]
this theme is awesome, but replace the style of inline codeblock would be better.
just like this :

```
/* inline codeblock */
code {
  font-size: 0.9em;
  background-color: var(--bg-color5);
	padding: .3em;
  	padding-top: 0.15em;
  	padding-bottom: 0.15em;
  /* border: 2px solid #666; */
  border-radius: 0.25rem;
  color: #f92672;
}
```

**Comment by gilbertohasnofb** [comment]
@uninstallHahaha Hi, thank you for your message, I'm happy to hear you like the theme. Also, thanks for the suggestion but I actually much prefer the current style. I think that just changing the background colour of a `code word` without changing the text colour works well (just like here on GitHub), and using the border helps identify those. Do feel free to customise your own copy of the theme, or fork it if you wish :smiley:

**Comment by gilbertohasnofb** [comment]
btw, you can wrap your code blocks on GitHub using three backticks before and after it (```) so that it displays as a code block. I edited your original report.
