### ISSUE TITLE
the theme does not appear theme list

### ISSUE THREAD

**Issue by simohakki** [gilbertohasnofb/typora-panda-theme#4]
Hi, I unzip the contents of `panda.zip` file under the directory `C:\Program Files\Typora\resources\app\style\themes` and I don't see the new theme appearing after restarting Typora. Do you have any idea where this might come from? 
i'm under windows 10, Typora 0.9.98(beta)
thanks

**Comment by stephanlamoureux** [comment]
The same thing happened to me, it works on Mac OS but not on Windows.

**Comment by gilbertohasnofb** [comment]
Hi, thank you to you both. I work mostly on Linux but I also have Windows installed and I will double check this soon. Could I just ask you to confirm that, once you extract the file, you see a file named `panda.css` and a folder named `panda` in your `themes` folder (the path in my screenshot is for Linux, make sure you are in the correct directory on Windows):

![image](https://user-images.githubusercontent.com/5700795/106454524-c810c380-6482-11eb-8028-cb34f8d728f9.png)

Also, can you see other themes in Typora which are installed on that same folder?

**Comment by gilbertohasnofb** [comment]
@simohakki Another thing, you mention the folder `C:\Program Files\Typora\resources\app\style\themes`. Are you sure that's the folder you must install themes on Windows? My themes on Windows are installed in the folder `C:\Windows\Users\USERNAME\AppData\Roaming\Typora\themes`.

Typora also has a dedicated button to open the themes folder in its configuration menu, see: https://theme.typora.io/doc/Install-Theme/

Please confirm if you still have issues with this theme after looking into these.

**Comment by simohakki** [comment]
> 
> 
> @simohakki Another thing, you mention the folder `C:\Program Files\Typora\resources\app\style\themes`. Are you sure that's the folder you must install themes on Windows? My themes on Windows are installed in the folder `C:\Windows\Users\USERNAME\AppData\Roaming\Typora\themes`.
> 
> Typora also has a dedicated button to open the themes folder in its configuration menu, see: https://theme.typora.io/doc/Install-Theme/
> 
> Please confirm if you still have issues with this theme after looking into these.

you're right, i just changed the themes under the `C:\Users\%username%\AppData\Roaming\Typora\themes` directory and it works now
Thank you !

**Comment by gilbertohasnofb** [comment]
No problems, glad it worked! Enjoy the theme :smile:
