### ISSUE TITLE
The selected text in a quote block is barely visible 

### ISSUE THREAD

**Issue by Korean-David** [gilbertohasnofb/typora-panda-theme#6]
The selected text in a quote block is barely visible since both are grey.
So could you make some changes so that they can be more readable?

**Comment by gilbertohasnofb** [comment]
Hi, thanks for the bug report. Indeed that's a problem. I'll take a look at this soon and let you know here when it's fixed.

**Comment by Korean-David** [comment]
> Hi, thanks for the bug report. Indeed that's a problem. I'll take a look at this soon and let you know here when it's fixed.

Thanks. And also, when texts with a link are selected, sometimes they are barely visible, too. 
(And the highlight color: orange, if you could teak that color a little bit, I think it may look better)

Thanks for this theme. I really like it.

**Comment by gilbertohasnofb** [comment]
@Korean-David I'm making some alterations to the theme now, would you like to give me your opinion on these changes before I push them? Here's an example of text **without** selection:

![image](https://user-images.githubusercontent.com/5700795/144706531-45832d82-5e37-46b1-814d-2af36deeb1c6.png)

The same with selected text:

![image](https://user-images.githubusercontent.com/5700795/144706539-88433b25-3df0-4ae0-86fc-cae8efe92373.png)

**Comment by Korean-David** [comment]
> @Korean-David I'm making some alterations to the theme now, would you like to give me your opinion on these changes before I push them? Here's an example of text **without** selection:

I personally feel that quoted texts don't need to be grey. Since it already has the blue code block, blue quoted texts can be more readable. 
Also, I think the highlight color (which is orange now) may look better if it is blue, being consistent with the theme's overall atmosphere.

**Comment by gilbertohasnofb** [comment]
@Korean-David Thanks for the feedback. I might be misunderstanding what you are saying, but I don't know what you mean by orange highlight colour. The highlight colour I used in the image above is a very pale blue, not orange. Are we looking at the same image?

As for the quoted text, I will experiment with those and see what I prefer, though I do like them just a little bit darker than the text. This is something easy to change in your own copy of this theme, if you'd like that.

**Comment by Korean-David** [comment]
Oh, sorry for the confusion. I was talking about a different highlight, ==text==, which is orange color.
<img width="372" alt="Screen Shot 2021-12-04 at 7 55 23 AM" src="https://user-images.githubusercontent.com/89657008/144712108-c2dd6689-d3d7-4c1e-8594-856087b26f17.png">

**Comment by gilbertohasnofb** [comment]
Ah, sorry, I see what you mean. I personally feel that the yellow/orange colour gives more emphasis to the highlight:

![image](https://user-images.githubusercontent.com/5700795/144712565-ad337d92-5352-4b55-80da-dd8ebe8e6a36.png)

Although blue does work well too:

![image](https://user-images.githubusercontent.com/5700795/144712770-67346b16-5391-43ed-a91a-14671a37f178.png)

I think I will keep the orange colour for now, but if you want to have blue in your own copy, simply replace line 2009 with `background-color: var(--code-blue-color);`. (edit: this line will be number 2007 in the new file after I push my modifications, as I removed some unneeded empty spaces from the file)

I'll push the selection highlight changes in a bit. Thanks for flagging this up with me!
